micronaut:
  application:
    name: fretes

grpc:
  server:
    health:
        enable: true

endpoints:
  all:
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
