micronaut:
  application:
    name: kassaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:7075/Aplicacao
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
