micronaut:
  application:
    name: fretesRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    fretes: # o canal chamado "fretes" que está na classe GrpcClientFactory e é usado no método fretesClientStub
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5
